{% set name = "winreg" %}
{% set version = "6.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/GiovanniDicanio/WinReg/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 44cc0f6b3e75bf8b8167f7e96e97e0cbd0da3ca2d622cfc72a37da8fc0f395c0

build:
  number: 0
  skip: true  # [not win]
  script: mkdir %LIBRARY_PREFIX%\include\winreg && cp WinReg\WinReg.hpp %LIBRARY_PREFIX%\include\winreg\

test:
  commands:
    - if not exist %LIBRARY_PREFIX%\include\winreg\WinReg.hpp (exit 1)  # [win]

about:
  home: https://github.com/GiovanniDicanio/WinReg
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Convenient high-level C++ wrapper around the Windows Registry API

extra:
  recipe-maintainers:
    - wolfv
