{% set name = "winreg" %}
{% set version = "5.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/GiovanniDicanio/WinReg/archive/refs/tags/v{{ version }}.tar.gz
  sha256: c86fd5433bb5a999fbc934ec5bc7f9e5adcb274de71dab084bd081d4d812dd11

build:
  number: 0
  skip: true  # [not win]
  script: cp WinReg\WinReg.hpp %LIBRARY_PREFIX%\include\

test:
  commands:
    - if not exist %LIBRARY_PREFIX%\include\WinReg.hpp (exit 1)  # [win]

about:
  home: https://github.com/GiovanniDicanio/WinReg
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Convenient high-level C++ wrapper around the Windows Registry API

extra:
  recipe-maintainers:
    - wolfv
