{% set name = "winreg" %}
{% set version = "6.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/GiovanniDicanio/WinReg/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d4118ccfd4f4edee29e0f6b3706979791ad537278e2f74818c150bb66f8fcc53

build:
  number: 0
  skip: true  # [not win]
  script: cp WinReg\WinReg.hpp %LIBRARY_PREFIX%\include\

test:
  commands:
    - if not exist %LIBRARY_PREFIX%\include\WinReg.hpp (exit 1)  # [win]

about:
  home: https://github.com/GiovanniDicanio/WinReg
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Convenient high-level C++ wrapper around the Windows Registry API

extra:
  recipe-maintainers:
    - wolfv
