context:
  name: winreg
  version: "6.3.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/GiovanniDicanio/WinReg/archive/refs/tags/v${{ version }}.tar.gz
  sha256: b92842cc37d3fe1a4d103929480045a40c39ba2efc15d7656f62e189d10d0bc4

build:
  number: 0
  skip: not win
  script: mkdir %LIBRARY_PREFIX%\include\winreg && cp WinReg\WinReg.hpp %LIBRARY_PREFIX%\include\winreg\

tests:
  - package_contents:
      include:
        - winreg/WinReg.hpp

about:
  homepage: https://github.com/GiovanniDicanio/WinReg
  license: MIT
  license_file: LICENSE
  summary: Convenient high-level C++ wrapper around the Windows Registry API

extra:
  recipe-maintainers:
    - wolfv
